title: AoJnnnの小窝
description: AoJnnn的NoBlog
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# 强制指定Markdown解析器
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 在这里更换你的背景图片URL！
background_image: https://AoJnnn.github.io/images/back.png
github_comments_repo: AoJnnn/AoJnnn.github.io