name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler: 2.4.21
          cache: true
          
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
          
      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --trace
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site